### PR TITLE
First release

### PR DESCRIPTION
**Pull request by SarahMalykke**
@jessb0t

### CODE REVIEW

**Review by jessb0t — DISMISSED** [review]

**Comment by jessb0t** [comment]
@georgebuzzell Initial release of putt-putt-dataset is ready for your review!  (I know we'll be updating the flanker task shortly.) 🤓

**Review by georgebuzzell — COMMENTED** [review]
Great start.

see comments and edits

**Comment by georgebuzzell** [comment]
@SarahMalykke please see edits and comments.

@jessb0t

**Review by jessb0t — APPROVED** [review]

**Comment by jessb0t** [comment]
Merging per @georgebuzzell !

**Pull request merged**
