### PR TITLE
Data Dictionary

### PR DESCRIPTION
**Pull request by SarahMalykke**
Hi @jessb0t 🙂 I added the Data Dictionary for putt-putt

### CODE REVIEW

**Comment by jessb0t** [comment]
@SarahMalykke Quick question: we haven't collected any participants yet, right?  That is, there is no reason to keep a copy of the older data dictionary because we didn't run any participants under that precise set of questions?

**Comment by SarahMalykke** [comment]
Yeah, no need to keep the older data dictionary 🙂  @jessb0t Did I not remove it properly?

**Comment by jessb0t** [comment]
@SarahMalykke Nope, you did it fine!  I was just checking to make sure I understood.  Since we are tweaking the surveys right now, I will wait to merge this until you can adjust initState, postTask, and covid. :)

**Review by jessb0t — APPROVED** [review]
Merging, @SarahMalykke !

**Pull request merged**
